cask_args appdir: '/Applications'

# base
cask "zen"
cask "spotify"
cask "font-hack-nerd-font"
cask "wezterm"
brew "nvim"
brew "vim"
brew "tmux"
brew "tmuxp"
brew "lazygit"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-autocomplete"
brew "reattach-to-user-namespace"
cask "hammerspoon"

# dev
brew "fzf"
brew "rg"
brew "fd"
brew "eza"
brew "curl"
brew "wget"
brew "golang"
brew "lua-language-server"
brew "typescript-language-server"
brew "pyright"
brew "pyenv-virtualenv"
brew "luarocks"
brew "autoconf"
brew "automake"
brew "cmake"
brew "gcc"
brew "watch"
brew "rust"

# system
cask "maccy"
brew "pass"
brew "hugo"

# work
brew "kind"
brew "grpcurl"
brew "k9s"
brew "awscli"
cask "docker"
cask "postman"
cask "postman-cli"
