# Prefix
set -g prefix C-a
bind C-a send-prefix

# General
set -g mouse on
set -s escape-time 1
set -g base-index 1
set -g pane-base-index 1
set -g display-panes-time 3000
set -g repeat-time 1000
set -g focus-events on
set -g automatic-rename off
setw -g mode-keys vi

# Hooks
set-hook -g client-focus-in                 'resize-window -A'
set-hook -g client-attached                 'resize-window -A'
set-hook -g client-resized                  'resize-window -A'
set-hook -g window-linked                   'refresh-client -S'
set-hook -g window-unlinked                 'refresh-client -S'
set-hook -g session-window-changed          'refresh-client -S'
set-hook -g session-created                 'refresh-client -S'
set-hook -g session-closed                  'refresh-client -S'
set-hook -g after-select-window             'refresh-client -S'
set-hook -g client-session-changed          'run-shell "~/.tmux/hooks/client-session-changed.sh"'

# Copy mode
bind y copy-mode
bind -T copy-mode-vi  v  send-keys -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# Panes — management
bind x kill-pane
bind Space run-shell "~/.tmux/panes/cycle-layout.sh"

# Panes — navigation
bind o select-pane -t :.+
bind O select-pane -t :.-
bind -r \; last-pane
bind -r Tab select-pane -t :.+ \; resize-pane -Z

# Windows — navigation
bind -r p select-window -t :-
bind -r n select-window -t :+
bind -r l last-window

# Windows — reordering
bind -r < swap-window -t -1 \; previous-window
bind -r > swap-window -t +1 \; next-window

# Windows — resizing
bind C-l resize-window -A

# Sessions
bind -r L switch-client -l
bind -r ) switch-client -n
bind -r ( switch-client -p

# Scripts
bind Enter      run-shell "~/.tmux/terminal.sh"
bind N          run-shell "~/.tmux/sessions/switch-to-next.sh"
bind P          run-shell "~/.tmux/sessions/switch-to-prev.sh"
bind E          run-shell "~/.tmux/panes/edit-before-paste-into.sh"
bind S          run-shell "~/.tmux/panes/swap.sh"
bind R          run-shell "~/.tmux/panes/record.sh"

# Appearance — panes
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=blue'
set -g window-style 'bg=colour236'
set -g window-active-style 'bg=colour235'

# Appearance — status bar
bind t set -g status
set -g status on
set -g status-interval 1
set -g status-position top
set -g status-style 'fg=white,bg=default,bold'
set -g message-style 'fg=default'
set -g message-command-style 'fg=default'

if-shell '[ "$(tmux -V | cut -c6- | cut -d. -f1)" -ge 3 ]' {
    set -g status 2
    set -g status-format[0] '#(~/.tmux/statusline/secondary.sh)'
    set -g status-format[1] '#(~/.tmux/statusline/primary.sh)'
} {
    set -g status-format[0] '#(~/.tmux/statusline/primary.sh)'
}

# Source
bind r source-file ~/.tmux.conf \; display-message "reloaded config"
